### ISSUE TITLE
KeyError: 'course_info'

### ISSUE THREAD

**Issue by mandichen** [openedx/edx-search#39]
I was trying to reindex a course while encountered with a warning saying 
"There were errors reindexing course."

I checked the log of cms, this is what I got:

Jan  4 08:16:01 vultr [service_variant=cms][edx.modulestore][env:sandbox] ERROR [vultr  25818] [courseware_index.py:267] - Indexing error encountered, courseware index may be out of date course-v1:edX+DemoX+Demo_Course - KeyError('course_info',)
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/courseware_index.py", line 255, in index
    cls.supplemental_index_information(modulestore, structure)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/courseware_index.py", line 403, in supplemental_index_information
    CourseAboutSearchIndexer.index_about_information(modulestore, structure)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/courseware_index.py", line 632, in index_about_information
    searcher.index(cls.DISCOVERY_DOCUMENT_TYPE, [course_info])
  File "/edx/app/edxapp/venvs/edxapp/src/edx-search/search/elastic.py", line 386, in index
    raise ex
KeyError: 'course_info'

**Comment by jzoldak** [comment]
@Lamicc what hash of edx-platform are you using? 
And what version of edx-search is installed? You can get this with `pip freeze | grep edx-search`

**Comment by raulperula** [comment]
I have the same problem with the same error message.

I am using a fullstack open edx version and the last version of edx-search.

I have followed the second installation step from the doc: http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/edx_search.html

I appreciate any help.

**Comment by Fatma-Sarhan** [comment]
i have the same error 
solution please ?

**Comment by changeforan** [comment]
Help , I got the same error.
Can anybody help me?
